### ISSUE TITLE
missing dependency?

### ISSUE THREAD

**Issue by marscher** [rmcgibbo/conda-hint#1]
``` python
Traceback (most recent call last):
  File "/home/marscher/miniconda/bin/conda-hint", line 6, in <module>
    from conda_hint import main
  File "/home/marscher/miniconda/lib/python3.4/site-packages/conda_hint/__init__.py", line 19, in <module>
    from typing import Dict, List, Tuple, Set, Union, Iterable
ImportError: No module named 'typing'
```

**Comment by marscher** [comment]
I actually didn't see that minimum requirement is Python-3.5. I guess this is solved by using the correct version?
